services:
  database:
    image: mongo:latest
    container_name: battlebanana-database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: battlebanana
      MONGO_INITDB_ROOT_PASSWORD: dev123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - battlebanana-network

  ollama:
    image: ollama/ollama:0.30.6
    container_name: battlebanana-ollama
    restart: unless-stopped
    gpus: all
    environment:
      OLLAMA_KEEP_ALIVE: 24h
      OLLAMA_HOST: 0.0.0.0:11434
    networks:
      - battlebanana-network
    volumes:
      - ollama_data:/root/.ollama

  bot:
    build: .
    container_name: battlebanana-bot
    restart: unless-stopped
    depends_on:
      - database
      - ollama
    volumes:
      - ./logs:/usr/src/app/logs
      - ./assets:/usr/src/app/assets
    networks:
      - battlebanana-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  ollama_data:
    driver: local


networks:
  battlebanana-network:
    driver: bridge
