services:
  ollama:
    image: ollama/ollama:0.30.6
    container_name: battlebanana-ollama
    restart: unless-stopped
    gpus: all
    environment:
      OLLAMA_KEEP_ALIVE: 24h
      OLLAMA_HOST: 0.0.0.0:11434
    networks:
      - battlebanana-network
    volumes:
      - ollama_data:/root/.ollama

  bot:
    build: .
    container_name: battlebanana-bot
    restart: unless-stopped
    depends_on:
      - ollama
    volumes:
      - ./logs:/usr/src/app/logs
      - ./assets:/usr/src/app/assets
    networks:
      - battlebanana-network
    labels:
      - io.portainer.accesscontrol.teams=BattleBanana

networks:
  battlebanana-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
